# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go fmt Check
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: './'
        gofmt-flags: '-l -d'

    - name: Clone TongSuo repository
      uses: actions/checkout@v3
      with:
        repository: Tongsuo-Project/Tongsuo
        path: tongsuo
        ref: 8.3-stable

    - name: Build  Tongsuo
      run: cd tongsuo &&  ./config --prefix=/opt/tongsuo -Wl,-rpath,/opt/tongsuo/lib  enable-ssl-trace enable-ec_elgamal enable-ntls && make -j && make install

    - name: Check Tongsuo lib
      run: ls /opt/tongsuo/lib

    - name: Check Tongsuo binary
      run: ldd /opt/tongsuo/bin/openssl 

    - name: Go Mod
      run: go mod tidy

    - name: Go vet Check
      run: go vet ./...

    - name: Build
      run: go build

    - name: Pre-Test
      run: cd tongsuo && git checkout 8.4-stable

    - name: Test
      run: go test -exec "env LD_LIBRARY_PATH=/opt/tongsuo/lib" ./...
