# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go fmt Check
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: './'
        gofmt-flags: '-l -d'

    - name: Clone Tongsuo
      uses: actions/checkout@v3
      with:
        repository: Tongsuo-Project/Tongsuo
        path: tongsuo
        ref: 8.3-stable

    - name: Build Tongsuo
      run: |
        cd tongsuo
        ./config --prefix=/opt/tongsuo --libdir=/opt/tongsuo/lib enable-ntls
        make -j4
        make install

    - name: Go Mod
      run: go mod tidy

    - name: Go vet Check
      run: LD_LIBRARY_PATH=/opt/tongsuo/lib CGO_CFLAGS="-Wall -I/opt/tongsuo/include -Wno-deprecated-declarations" CGO_LDFLAGS="-L/opt/tongsuo/lib" go vet ./...

    - name: Build
      run: CGO_CFLAGS="-Wall -I/opt/tongsuo/include -Wno-deprecated-declarations" CGO_LDFLAGS="-L/opt/tongsuo/lib" go build

    - name: Test
      run: LD_LIBRARY_PATH=/opt/tongsuo/lib CGO_CFLAGS="-Wall -I/opt/tongsuo/include -Wno-deprecated-declarations" CGO_LDFLAGS="-L/opt/tongsuo/lib" go test ./...

  build_static:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Clone Tongsuo
      uses: actions/checkout@v3
      with:
        repository: Tongsuo-Project/Tongsuo
        path: tongsuo
        ref: 8.3-stable

    - name: Build Tongsuo Static
      run: |
        cd tongsuo
        ./config --prefix=/opt/tongsuo --libdir=/opt/tongsuo/lib enable-ntls no-shared
        make -j4
        make install

    - name: Test
      run: LD_LIBRARY_PATH=/opt/tongsuo/lib CGO_CFLAGS="-Wall -I/opt/tongsuo/include -Wno-deprecated-declarations" CGO_LDFLAGS="-L/opt/tongsuo/lib" go test ./...
